version: "3.9"
services:
  node_app:
    container_name: node_app
    build: .
    image: distrib/backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=your_password  
      - DB_NAME=mydb
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRES_IN=24h
    depends_on:
      - mysql
    restart: always
  
  mysql:
    container_name: "mysql"
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=mydb
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:




